### ISSUE TITLE
Several issues with start_climate service

### ISSUE THREAD

**Issue by zachberger** [dahlb/ha_kia_hyundai#113]
**Region and Brand of car**
2024 Kia Niro EV - North America

**Describe the bug**
Unable to call start_climate service from an automation. A few things I noticed: 

1. After updating to 1.8.7, existing automation fail since duration is set. (first screenshot below)
1. After removing duration, `Vehicle.start_climate` fails because duration is not set (second screenshot)
1. If I specify the vehicle (as prompted to in the Automation builder) the service fails because it wasn't expecting a device_id

**Debug logs if an error occurred**
First error:

```
Warm Car: Error executing script. Invalid data for call_service at pos 1: extra keys not allowed @ data['duration']
```

Second error:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 655, in async_trigger
    await self.action_script.async_run(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1578, in async_run
    return await asyncio.shield(run.async_run())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 420, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 470, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 493, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 704, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 666, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2067, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2104, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ha_kia_hyundai/__init__.py", line 111, in async_handle_start_climate
    await hass.async_create_task(
  File "/config/custom_components/ha_kia_hyundai/vehicle.py", line 33, in mark_used_wrapper
    await func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
TypeError: Vehicle.start_climate() missing 1 required positional argument: 'duration'
```
Third error:

```
Warm Car: Error executing script. Invalid data for call_service at pos 1: extra keys not allowed @ data['device_id']
```

**To Reproduce**
Steps to reproduce the first issue:
1. With 1.8.6 or lower of the component installed create an automation that calls the `start_climate` service and specify duration
2. Upgrade to 1.8.7
3. Try to run the automation 

Steps to reproduce the second issue:
1. With 1.8.7 of the component installed create an automation that calls the `start_climate` service 
2. Try to run the automation 

Steps to reproduce the third issue:
1. With 1.8.7 of the component installed create an automation that calls the `start_climate` service and specify the vehicle
2. Try to run the automation 

**Expected behavior**
Climate is started on the vehicle

**Screenshots**

![Screenshot 2023-12-20 at 5 30 28 PM](https://github.com/dahlb/ha_kia_hyundai/assets/1634878/fb0c81be-3606-46f3-9d25-56bcd8f0a8ac)
![Screenshot 2023-12-20 at 5 28 57 PM](https://github.com/dahlb/ha_kia_hyundai/assets/1634878/734bb83b-e33e-4637-91a4-9760ea0a2d57)
![Screenshot 2023-12-20 at 5 29 03 PM](https://github.com/dahlb/ha_kia_hyundai/assets/1634878/cd02497f-3851-4b63-ae12-46f595425c4d)

**Additional context**

**Comment by dahlb** [comment]
Sorry, 1.8.8 should resolve the error about duration, the key has been fully removed as the api was just ignoring it anyway

thanks for writing it up

**Comment by dahlb** [comment]
@shmulyeng device_id is only expected if you have two cars on the same kia account; if you have only one it shouldn't be specified
