### ISSUE TITLE
KeyError: 'pin'

### ISSUE THREAD

**Issue by jakecolman** [dahlb/ha_kia_hyundai#44]
**Region and Brand of car**
US / Kia Niro

**Describe the bug**
After entering credentials you get "unknown error".

**Debug logs if an error occurred**

...skipping...
2021-12-28 12:45:57 DEBUG (PysherScheduler) [websocket] send: b'\x81\xa4\xe0\x87\xcb\xf7\x9b\xa5\xae\x81\x85\xe9\xbf\xd5\xda\xa7\xe9\x87\x95\xf4\xa3\x92\x92\xbd\xbb\x9e\x8e\xe0\xe9\xdb\xc0\xa5\xaf\x96\x94\xe6\xe9\xcd\xc0\xa5\xe9\x8a'
2021-12-28 12:45:57 INFO (PysherEventLoop) [pysher.connection] Connection: Message - {"event":"pusher:pong","data":"{}"}
2021-12-28 12:45:57 INFO (PysherEventLoop) [pysher.connection] Connection: pong from pusher
2021-12-28 12:46:57 DEBUG (PysherEventLoop) [websocket] send: b'\x8a\x80\x1dE\x98!'
2021-12-28 12:47:23 WARNING (MainThread) [homeassistant.helpers.entity] Update of climate.guest_room is taking over 10 seconds
2021-12-28 12:47:57 INFO (PysherScheduler) [pysher.connection] Connection: ping to pusher
2021-12-28 12:47:57 DEBUG (PysherScheduler) [websocket] send: b'\x81\xa4\xd8S\x13\xd3\xa3qv\xa5\xbd=g\xf1\xe2s1\xa3\xad {\xb6\xaaic\xba\xb641\xff\xf8qw\xb2\xac21\xe9\xf8q1\xae'
2021-12-28 12:47:57 INFO (PysherEventLoop) [pysher.connection] Connection: Message - {"event":"pusher:pong","data":"{}"}
2021-12-28 12:47:57 INFO (PysherEventLoop) [pysher.connection] Connection: pong from pusher
2021-12-28 12:48:57 DEBUG (PysherEventLoop) [websocket] send: b'\x8a\x80\x02\xe5VU'
2021-12-28 12:49:08 DEBUG (MainThread) [custom_components.ha_kia_hyundai.api_cloud_util] US KIA in use
2021-12-28 12:49:18 DEBUG (MainThread) [custom_components.ha_kia_hyundai.api_cloud_util] US KIA in use
2021-12-28 12:49:18 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 181, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 157, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 252, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/ha_kia_hyundai/config_flow.py", line 136, in async_step_auth
    if user_input[CONF_PIN] is not None:
KeyError: 'pin'

**To Reproduce**
1. Enter initial configuration screen
2. Select "US" and "Kia".  Press Enter.
3. Enter credentials

**Expected behavior**
The credentials should be accepted and I should be prompted to select my vehicle.

**Additional context**
Commenting out lines 136 and 137 avoids the issue.  My guess is that PIN is only needed for Canada so for US the dictionary was not set up.

**Comment by dahlb** [comment]
thanks for filing such a detailed issue, the fix is released in https://github.com/dahlb/ha_kia_hyundai/commit/d49319eee969419274477874193ec1d9dbf7528b sorry HACS may not be showing it up yet, you can also just git clone it down to ensure you have the latest code
