### ISSUE TITLE
UNLOCK Request Fails

### ISSUE THREAD

**Issue by jakecolman** [dahlb/ha_kia_hyundai#47]
**Region and Brand of car**
US / Kia Niro

**Describe the bug**
The UNLOCK requests displays a "failed to call service..." message.  I am posting the issue because the traceback shows that something unexpected happened, as opposed to this being a feature that is not yet implemented,

**Debug logs if an error occurred**

2021-12-29 19:34:31 DEBUG (MainThread) [kia_hyundai_api.us_kia] sending https://api.owners.kia.com/apigw/v1/rems/door/unlock request
2021-12-29 19:34:32 DEBUG (MainThread) [kia_hyundai_api.us_kia] response headers:<CIMultiDictProxy('Server': 'KMA', 'Date': 'Thu, 30 Dec 2021 00:34:32 GMT', 'Content-Length': '99', 'Content-Type': 'application/json', 'Xid': '2243dae3-80ca-4b28-8916-fe2d7bd699fe')>
2021-12-29 19:34:32 DEBUG (MainThread) [kia_hyundai_api.us_kia] response text:{"status":{"statusCode":1,"errorType":1,"errorCode":1072,"errorMessage":"Vehicle is not enrolled"}}
2021-12-29 19:34:32 DEBUG (MainThread) [kia_hyundai_api.us_kia] error: unknown error response {"status":{"statusCode":1,"errorType":1,"errorCode":1072,"errorMessage":"Vehicle is not enrolled"}}
2021-12-29 19:34:32 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [1659636776] api error:Vehicle is not enrolled
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 209, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 663, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 896, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 700, in _handle_entity_call
    await result
  File "/config/custom_components/ha_kia_hyundai/lock.py", line 51, in async_unlock
    await self.hass.async_create_task(
  File "/config/custom_components/ha_kia_hyundai/vehicle.py", line 201, in lock_action
    await self.api_cloud.lock(vehicle=self, action=action)
  File "/config/custom_components/ha_kia_hyundai/api_cloud_us_kia.py", line 30, in request_with_active_session_wrapper
    return await func(*args, **kwargs)
  File "/config/custom_components/ha_kia_hyundai/api_cloud_us_kia.py", line 279, in lock
    xid = await self.api.unlock(session_id, vehicle.key)
  File "/usr/local/lib/python3.9/site-packages/kia_hyundai_api/us_kia.py", line 216, in unlock
    response = await self._get_request_with_logging_and_errors_raised(
  File "/usr/local/lib/python3.9/site-packages/kia_hyundai_api/us_kia.py", line 47, in request_with_logging_wrapper
    raise ClientError(f"api error:{response_json['status']['errorMessage']}")
aiohttp.client_exceptions.ClientError: api error:Vehicle is not enrolled

**Additional context**
My car is enrolled in UVO Connect, at least for now, and lock/unlock works correctly from my Phone App.

**Comment by dahlb** [comment]
I just checked it doesn't say not enrolled on my installation, me guess is something in the api call is different with your car likely either because it is on the trial or because it is not electric (CA has different api endpoints for EV vs NON-EV for climate start but not lock).  Other possibility is the api is just returning invalid status but the action was successful (not the best API implementation imo, did you check the car to see if the lock changed? (if you invoke unlock the doors automatically re-lock  shortly after similar to if you use the key remote to unlock the doors but don't open any of them for a few minutes.

if you have some experience with development especially on android, I can walk you through setting up a simulator to sniff the api traffic. If not we should probably table this for now, until we at least resolve any other problems you're encountering as the only other solution I can think of is for you to set a temporary password and email me your credentials for an hour or two so I can sniff the in app traffic.

**Comment by americanpinko** [comment]
Same thing is observed for mine.
Fully Electric, enrolled in paid subscription, fails

**Comment by dahlb** [comment]
stale
