### ISSUE TITLE
Missing vehicle ID, Hyundai Ioniq EV 2021, Canada

### ISSUE THREAD

**Issue by terrycalderbank** [dahlb/ha_kia_hyundai#53]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/dahlb/ha_kia_hyundai/blob/master/README.md
**Region and Brand of car**

**Describe the bug**

**Debug logs if an error occurred**
This error originated from a custom integration.

Logger: custom_components.ha_kia_hyundai.vehicle
Source: custom_components/ha_kia_hyundai/api_cloud_ca.py:317
Integration: Kia/Hyundai (documentation, issues)
First occurred: 3:38:25 PM (2 occurrences)
Last logged: 3:38:38 PM

Unexpected error fetching Vehicle XkfhdHMVuCM2Ir4ss1Ju3Q== data: _post_request_with_logging_and_errors_raised() missing 1 required positional argument: 'vehicle_id'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/ha_kia_hyundai/vehicle.py", line 117, in async_update_data
    await self.api_cloud.update(vehicle=self)
  File "/config/custom_components/ha_kia_hyundai/api_cloud_ca.py", line 33, in request_with_active_session_wrapper
    return await func(*args, **kwargs)
  File "/config/custom_components/ha_kia_hyundai/api_cloud_ca.py", line 317, in update
    pin_token = await self.api.get_pin_token(
  File "/usr/local/lib/python3.9/site-packages/kia_hyundai_api/ca.py", line 184, in get_pin_token
    response = await self._post_request_with_logging_and_errors_raised(
  File "/usr/local/lib/python3.9/site-packages/kia_hyundai_api/ca.py", line 33, in request_with_logging_wrapper
    response = await func(*args, **kwargs)
TypeError: _post_request_with_logging_and_errors_raised() missing 1 required positional argument: 'vehicle_id'

Outlined here: https://github.com/dahlb/ha_kia_hyundai/blob/master/README.m

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by dahlb** [comment]
I pushed a fix up to master, thanks for writing up this bug. Please let me know if the fix works for you.

**Comment by terrycalderbank** [comment]
One more here, I think I installed from master.

```
Logger: custom_components.ha_kia_hyundai.vehicle
Source: custom_components/ha_kia_hyundai/api_cloud_ca.py:320
Integration: Kia/Hyundai ([documentation](https://github.com/dahlb/ha_kia_hyundai), [issues](https://github.com/dahlb/ha_kia_hyundai/issues))
First occurred: 6:05:06 PM (12 occurrences)
Last logged: 6:16:33 PM

Unexpected error fetching Vehicle XkfhdHMVuCM2Ir4ss1Ju3Q== data: Cannot serialize non-str key {'pAuth': 'wwLlUSpszpLuBNjAMAPruuQukiPbCnNA'}
Unexpected error fetching Vehicle XkfhdHMVuCM2Ir4ss1Ju3Q== data: Cannot serialize non-str key {'pAuth': 'vqMbhPVspKOIfDZBsvFvZnvHxlEgcaEL'}
Unexpected error fetching Vehicle XkfhdHMVuCM2Ir4ss1Ju3Q== data: Cannot serialize non-str key {'pAuth': 'INvGVbfkKFCWrvkfksjYUDguCJsNquUI'}
Unexpected error fetching Vehicle XkfhdHMVuCM2Ir4ss1Ju3Q== data: Cannot serialize non-str key {'pAuth': 'iGowUCKSBmvnQxiRGdqDrqjCSgihSFxV'}
Unexpected error fetching Vehicle XkfhdHMVuCM2Ir4ss1Ju3Q== data: Cannot serialize non-str key {'pAuth': 'ljYeUNIhUhqRwSJyqQSqQKgZdwWNKNLY'}
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/ha_kia_hyundai/vehicle.py", line 117, in async_update_data
    await self.api_cloud.update(vehicle=self)
  File "/config/custom_components/ha_kia_hyundai/api_cloud_ca.py", line 33, in request_with_active_session_wrapper
    return await func(*args, **kwargs)
  File "/config/custom_components/ha_kia_hyundai/api_cloud_ca.py", line 320, in update
    api_vehicle_location = await self.api.get_location(
  File "/usr/local/lib/python3.9/site-packages/kia_hyundai_api/ca.py", line 199, in get_location
    response = await self._post_request_with_logging_and_errors_raised(
  File "/usr/local/lib/python3.9/site-packages/kia_hyundai_api/ca.py", line 30, in request_with_logging_wrapper
    response = await func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/kia_hyundai_api/ca.py", line 130, in _post_request_with_logging_and_errors_raised
    return await self.api_session.post(url=url, json=json_body, headers=headers)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 557, in _request
    resp = await req.send(conn)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 669, in send
    await writer.write_headers(status_line, self.headers)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/http_writer.py", line 130, in write_headers
    buf = _serialize_headers(status_line, headers)
  File "aiohttp/_http_writer.pyx", line 132, in aiohttp._http_writer._serialize_headers
  File "aiohttp/_http_writer.pyx", line 109, in aiohttp._http_writer.to_str
TypeError: Cannot serialize non-str key {'pAuth': 'KLvfJhJVpkefMHKZKyCNyfMBdQHRcAGn'}
```

**Comment by dahlb** [comment]
I've added a second fix based on your latest error trace. Please let me know if this fix works for you.

**Comment by terrycalderbank** [comment]
![Screenshot from 2022-02-06 19-34-42](https://user-images.githubusercontent.com/22903165/152720617-00253625-6d09-45aa-8b5c-03a77a52439c.png)

Just got this, will investigate and report back.
