### ISSUE TITLE
Unable to get SyncDate

### ISSUE THREAD

**Issue by 0bmay** [dahlb/ha_kia_hyundai#67]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/dahlb/ha_kia_hyundai/blob/master/README.md
**Region and Brand of car**
US, KIA Soul EV

**Describe the bug**
Loading the custom component in HA fails causing the component to not load. Looks like KIA may have changed the output of the returned json data and it no longer includes syncDate, possibly others. Just a guess.. will try to load the data in the api project. Error started today. 

**Debug logs if an error occurred**
2023-02-15 16:32:58.717 ERROR (MainThread) [custom_components.ha_kia_hyundai.vehicle] Unexpected error fetching Vehicle 0***** data: 'NoneType' object is not subscriptable
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
self.data = await self._async_update_data()
File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/update_coordinator.py", line 195, in _async_update_data
return await self.update_method()
File "/home/homeassistant/.homeassistant/custom_components/ha_kia_hyundai/vehicle.py", line 116, in async_update_data
await self.api_cloud.update(vehicle=self)
File "/home/homeassistant/.homeassistant/custom_components/ha_kia_hyundai/api_cloud_us_kia.py", line 32, in request_with_active_session_wrapper
return await func(*args, **kwargs)
File "/home/homeassistant/.homeassistant/custom_components/ha_kia_hyundai/api_cloud_us_kia.py", line 120, in update
last_updated_str=vehicle_status["syncDate"]["utc"],
TypeError: 'NoneType' object is not subscriptable
2023-02-15 16:32:58.722 DEBUG (MainThread) [custom_components.ha_kia_hyundai.vehicle] Finished fetching Vehicle 0***** data in 0.326 seconds (success: False)

**To Reproduce**
1. Restart HA
2. See error

**Expected behavior**
custom component to load without issue

**Screenshots**

**Additional context**

Running HA 2023.2.2 and ha_kia_hyundai v1.7.3

**Comment by dahlb** [comment]
looks like they have changed the api parameters and have blocked access to debug on android devices to see the new parameters so this will likely take a while to find a fix.

<img width="388" alt="Screenshot 2023-02-15 at 9 26 25 PM" src="https://user-images.githubusercontent.com/54117/219252491-88f899fc-e378-49bc-815a-0eb473ed1256.png">

**Comment by 0bmay** [comment]
It's blocked on the iOS app too.. :(

**Comment by 0bmay** [comment]
looks like it might be possible to grab the api calls from the website...

https://owners.kia.com/apps/services/owners/getvehicleinfo.html/vehicle/1/maintenance/1/vehicleFeature/1/airTempRange/1/seatHeatCoolOption/1/enrollment/1/dtc/1/vehicleStatus/1/weather/1/location/1 

looks like it returns similar data to what is gathered from the api

**Comment by dahlb** [comment]
android's slightly older version 6.0.1 isn't blocked, using it I was able to identify the status data is being blocked unless enrollment is requested too, not sure if this is a bug on kia's side or a way to ensure active subscriptions, either way about to release a fix :)

**Comment by dahlb** [comment]
fixed in 1.7.4. Thanks for writing this up, this ticket helped resolve this very quickly

**Comment by 0bmay** [comment]
Awesome! Thank you for the quick fix!

**Comment by 0bmay** [comment]
Works as expected. Thank you again!
